baseURL = 'https://tomsik.cz'
languageCode = 'en-us'
title = 'Kamil Tomšík'

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
[[menu.nav]]
name = "Blog"
url = "/posts/"
weight = 2
[[menu.nav]]
name = "About"
url = "/about/"
weight = 3

[[menu.social]]
name = "Twitter"
url = "https://twitter.com/cztomsik"
weight = 1

[[menu.social]]
name = "GitHub"
url = "https://github.com/cztomsik"
weight = 2

[[menu.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/cztomsik/"
weight = 3
